/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-07-01 at 02:45:45 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.comercioendpoint;

/**
 * Service definition for Comercioendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ComercioendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Comercioendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the comercioendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "comercioendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Comercioendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Comercioendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getComercio".
   *
   * This request holds the parameters needed by the the comercioendpoint server.  After setting any
   * optional parameters, call the {@link GetComercio#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetComercio getComercio(java.lang.String id) throws java.io.IOException {
    GetComercio result = new GetComercio(id);
    initialize(result);
    return result;
  }

  public class GetComercio extends ComercioendpointRequest<com.fortmin.proshopping.comercioendpoint.model.Comercio> {

    private static final String REST_PATH = "comercio/{id}";

    /**
     * Create a request for the method "getComercio".
     *
     * This request holds the parameters needed by the the comercioendpoint server.  After setting any
     * optional parameters, call the {@link GetComercio#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetComercio#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetComercio(java.lang.String id) {
      super(Comercioendpoint.this, "GET", REST_PATH, null, com.fortmin.proshopping.comercioendpoint.model.Comercio.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetComercio setAlt(java.lang.String alt) {
      return (GetComercio) super.setAlt(alt);
    }

    @Override
    public GetComercio setFields(java.lang.String fields) {
      return (GetComercio) super.setFields(fields);
    }

    @Override
    public GetComercio setKey(java.lang.String key) {
      return (GetComercio) super.setKey(key);
    }

    @Override
    public GetComercio setOauthToken(java.lang.String oauthToken) {
      return (GetComercio) super.setOauthToken(oauthToken);
    }

    @Override
    public GetComercio setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetComercio) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetComercio setQuotaUser(java.lang.String quotaUser) {
      return (GetComercio) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetComercio setUserIp(java.lang.String userIp) {
      return (GetComercio) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetComercio setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetComercio set(String parameterName, Object value) {
      return (GetComercio) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertComercio".
   *
   * This request holds the parameters needed by the the comercioendpoint server.  After setting any
   * optional parameters, call the {@link InsertComercio#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.fortmin.proshopping.comercioendpoint.model.Comercio}
   * @return the request
   */
  public InsertComercio insertComercio(com.fortmin.proshopping.comercioendpoint.model.Comercio content) throws java.io.IOException {
    InsertComercio result = new InsertComercio(content);
    initialize(result);
    return result;
  }

  public class InsertComercio extends ComercioendpointRequest<com.fortmin.proshopping.comercioendpoint.model.Comercio> {

    private static final String REST_PATH = "comercio";

    /**
     * Create a request for the method "insertComercio".
     *
     * This request holds the parameters needed by the the comercioendpoint server.  After setting any
     * optional parameters, call the {@link InsertComercio#execute()} method to invoke the remote
     * operation. <p> {@link InsertComercio#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.fortmin.proshopping.comercioendpoint.model.Comercio}
     * @since 1.13
     */
    protected InsertComercio(com.fortmin.proshopping.comercioendpoint.model.Comercio content) {
      super(Comercioendpoint.this, "POST", REST_PATH, content, com.fortmin.proshopping.comercioendpoint.model.Comercio.class);
    }

    @Override
    public InsertComercio setAlt(java.lang.String alt) {
      return (InsertComercio) super.setAlt(alt);
    }

    @Override
    public InsertComercio setFields(java.lang.String fields) {
      return (InsertComercio) super.setFields(fields);
    }

    @Override
    public InsertComercio setKey(java.lang.String key) {
      return (InsertComercio) super.setKey(key);
    }

    @Override
    public InsertComercio setOauthToken(java.lang.String oauthToken) {
      return (InsertComercio) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertComercio setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertComercio) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertComercio setQuotaUser(java.lang.String quotaUser) {
      return (InsertComercio) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertComercio setUserIp(java.lang.String userIp) {
      return (InsertComercio) super.setUserIp(userIp);
    }

    @Override
    public InsertComercio set(String parameterName, Object value) {
      return (InsertComercio) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listComercio".
   *
   * This request holds the parameters needed by the the comercioendpoint server.  After setting any
   * optional parameters, call the {@link ListComercio#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListComercio listComercio() throws java.io.IOException {
    ListComercio result = new ListComercio();
    initialize(result);
    return result;
  }

  public class ListComercio extends ComercioendpointRequest<com.fortmin.proshopping.comercioendpoint.model.CollectionResponseComercio> {

    private static final String REST_PATH = "comercio";

    /**
     * Create a request for the method "listComercio".
     *
     * This request holds the parameters needed by the the comercioendpoint server.  After setting any
     * optional parameters, call the {@link ListComercio#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListComercio#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListComercio() {
      super(Comercioendpoint.this, "GET", REST_PATH, null, com.fortmin.proshopping.comercioendpoint.model.CollectionResponseComercio.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListComercio setAlt(java.lang.String alt) {
      return (ListComercio) super.setAlt(alt);
    }

    @Override
    public ListComercio setFields(java.lang.String fields) {
      return (ListComercio) super.setFields(fields);
    }

    @Override
    public ListComercio setKey(java.lang.String key) {
      return (ListComercio) super.setKey(key);
    }

    @Override
    public ListComercio setOauthToken(java.lang.String oauthToken) {
      return (ListComercio) super.setOauthToken(oauthToken);
    }

    @Override
    public ListComercio setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListComercio) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListComercio setQuotaUser(java.lang.String quotaUser) {
      return (ListComercio) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListComercio setUserIp(java.lang.String userIp) {
      return (ListComercio) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListComercio setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListComercio setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListComercio set(String parameterName, Object value) {
      return (ListComercio) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeComercio".
   *
   * This request holds the parameters needed by the the comercioendpoint server.  After setting any
   * optional parameters, call the {@link RemoveComercio#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveComercio removeComercio(java.lang.String id) throws java.io.IOException {
    RemoveComercio result = new RemoveComercio(id);
    initialize(result);
    return result;
  }

  public class RemoveComercio extends ComercioendpointRequest<Void> {

    private static final String REST_PATH = "comercio/{id}";

    /**
     * Create a request for the method "removeComercio".
     *
     * This request holds the parameters needed by the the comercioendpoint server.  After setting any
     * optional parameters, call the {@link RemoveComercio#execute()} method to invoke the remote
     * operation. <p> {@link RemoveComercio#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveComercio(java.lang.String id) {
      super(Comercioendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveComercio setAlt(java.lang.String alt) {
      return (RemoveComercio) super.setAlt(alt);
    }

    @Override
    public RemoveComercio setFields(java.lang.String fields) {
      return (RemoveComercio) super.setFields(fields);
    }

    @Override
    public RemoveComercio setKey(java.lang.String key) {
      return (RemoveComercio) super.setKey(key);
    }

    @Override
    public RemoveComercio setOauthToken(java.lang.String oauthToken) {
      return (RemoveComercio) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveComercio setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveComercio) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveComercio setQuotaUser(java.lang.String quotaUser) {
      return (RemoveComercio) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveComercio setUserIp(java.lang.String userIp) {
      return (RemoveComercio) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveComercio setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveComercio set(String parameterName, Object value) {
      return (RemoveComercio) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateComercio".
   *
   * This request holds the parameters needed by the the comercioendpoint server.  After setting any
   * optional parameters, call the {@link UpdateComercio#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.fortmin.proshopping.comercioendpoint.model.Comercio}
   * @return the request
   */
  public UpdateComercio updateComercio(com.fortmin.proshopping.comercioendpoint.model.Comercio content) throws java.io.IOException {
    UpdateComercio result = new UpdateComercio(content);
    initialize(result);
    return result;
  }

  public class UpdateComercio extends ComercioendpointRequest<com.fortmin.proshopping.comercioendpoint.model.Comercio> {

    private static final String REST_PATH = "comercio";

    /**
     * Create a request for the method "updateComercio".
     *
     * This request holds the parameters needed by the the comercioendpoint server.  After setting any
     * optional parameters, call the {@link UpdateComercio#execute()} method to invoke the remote
     * operation. <p> {@link UpdateComercio#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.fortmin.proshopping.comercioendpoint.model.Comercio}
     * @since 1.13
     */
    protected UpdateComercio(com.fortmin.proshopping.comercioendpoint.model.Comercio content) {
      super(Comercioendpoint.this, "PUT", REST_PATH, content, com.fortmin.proshopping.comercioendpoint.model.Comercio.class);
    }

    @Override
    public UpdateComercio setAlt(java.lang.String alt) {
      return (UpdateComercio) super.setAlt(alt);
    }

    @Override
    public UpdateComercio setFields(java.lang.String fields) {
      return (UpdateComercio) super.setFields(fields);
    }

    @Override
    public UpdateComercio setKey(java.lang.String key) {
      return (UpdateComercio) super.setKey(key);
    }

    @Override
    public UpdateComercio setOauthToken(java.lang.String oauthToken) {
      return (UpdateComercio) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateComercio setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateComercio) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateComercio setQuotaUser(java.lang.String quotaUser) {
      return (UpdateComercio) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateComercio setUserIp(java.lang.String userIp) {
      return (UpdateComercio) super.setUserIp(userIp);
    }

    @Override
    public UpdateComercio set(String parameterName, Object value) {
      return (UpdateComercio) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Comercioendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Comercioendpoint}. */
    @Override
    public Comercioendpoint build() {
      return new Comercioendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ComercioendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setComercioendpointRequestInitializer(
        ComercioendpointRequestInitializer comercioendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(comercioendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
