/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-07-01 at 02:46:11 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.paqueteendpoint;

/**
 * Service definition for Paqueteendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PaqueteendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Paqueteendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the paqueteendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "paqueteendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Paqueteendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Paqueteendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPaquete".
   *
   * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
   * optional parameters, call the {@link GetPaquete#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPaquete getPaquete(java.lang.String id) throws java.io.IOException {
    GetPaquete result = new GetPaquete(id);
    initialize(result);
    return result;
  }

  public class GetPaquete extends PaqueteendpointRequest<com.fortmin.proshopping.paqueteendpoint.model.Paquete> {

    private static final String REST_PATH = "paquete/{id}";

    /**
     * Create a request for the method "getPaquete".
     *
     * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
     * optional parameters, call the {@link GetPaquete#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPaquete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPaquete(java.lang.String id) {
      super(Paqueteendpoint.this, "GET", REST_PATH, null, com.fortmin.proshopping.paqueteendpoint.model.Paquete.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPaquete setAlt(java.lang.String alt) {
      return (GetPaquete) super.setAlt(alt);
    }

    @Override
    public GetPaquete setFields(java.lang.String fields) {
      return (GetPaquete) super.setFields(fields);
    }

    @Override
    public GetPaquete setKey(java.lang.String key) {
      return (GetPaquete) super.setKey(key);
    }

    @Override
    public GetPaquete setOauthToken(java.lang.String oauthToken) {
      return (GetPaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPaquete setQuotaUser(java.lang.String quotaUser) {
      return (GetPaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPaquete setUserIp(java.lang.String userIp) {
      return (GetPaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetPaquete setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPaquete set(String parameterName, Object value) {
      return (GetPaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPaquete".
   *
   * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
   * optional parameters, call the {@link InsertPaquete#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.fortmin.proshopping.paqueteendpoint.model.Paquete}
   * @return the request
   */
  public InsertPaquete insertPaquete(com.fortmin.proshopping.paqueteendpoint.model.Paquete content) throws java.io.IOException {
    InsertPaquete result = new InsertPaquete(content);
    initialize(result);
    return result;
  }

  public class InsertPaquete extends PaqueteendpointRequest<com.fortmin.proshopping.paqueteendpoint.model.Paquete> {

    private static final String REST_PATH = "paquete";

    /**
     * Create a request for the method "insertPaquete".
     *
     * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
     * optional parameters, call the {@link InsertPaquete#execute()} method to invoke the remote
     * operation. <p> {@link InsertPaquete#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.fortmin.proshopping.paqueteendpoint.model.Paquete}
     * @since 1.13
     */
    protected InsertPaquete(com.fortmin.proshopping.paqueteendpoint.model.Paquete content) {
      super(Paqueteendpoint.this, "POST", REST_PATH, content, com.fortmin.proshopping.paqueteendpoint.model.Paquete.class);
    }

    @Override
    public InsertPaquete setAlt(java.lang.String alt) {
      return (InsertPaquete) super.setAlt(alt);
    }

    @Override
    public InsertPaquete setFields(java.lang.String fields) {
      return (InsertPaquete) super.setFields(fields);
    }

    @Override
    public InsertPaquete setKey(java.lang.String key) {
      return (InsertPaquete) super.setKey(key);
    }

    @Override
    public InsertPaquete setOauthToken(java.lang.String oauthToken) {
      return (InsertPaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPaquete setQuotaUser(java.lang.String quotaUser) {
      return (InsertPaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPaquete setUserIp(java.lang.String userIp) {
      return (InsertPaquete) super.setUserIp(userIp);
    }

    @Override
    public InsertPaquete set(String parameterName, Object value) {
      return (InsertPaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPaquete".
   *
   * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
   * optional parameters, call the {@link ListPaquete#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPaquete listPaquete() throws java.io.IOException {
    ListPaquete result = new ListPaquete();
    initialize(result);
    return result;
  }

  public class ListPaquete extends PaqueteendpointRequest<com.fortmin.proshopping.paqueteendpoint.model.CollectionResponsePaquete> {

    private static final String REST_PATH = "paquete";

    /**
     * Create a request for the method "listPaquete".
     *
     * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
     * optional parameters, call the {@link ListPaquete#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPaquete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPaquete() {
      super(Paqueteendpoint.this, "GET", REST_PATH, null, com.fortmin.proshopping.paqueteendpoint.model.CollectionResponsePaquete.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPaquete setAlt(java.lang.String alt) {
      return (ListPaquete) super.setAlt(alt);
    }

    @Override
    public ListPaquete setFields(java.lang.String fields) {
      return (ListPaquete) super.setFields(fields);
    }

    @Override
    public ListPaquete setKey(java.lang.String key) {
      return (ListPaquete) super.setKey(key);
    }

    @Override
    public ListPaquete setOauthToken(java.lang.String oauthToken) {
      return (ListPaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPaquete setQuotaUser(java.lang.String quotaUser) {
      return (ListPaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPaquete setUserIp(java.lang.String userIp) {
      return (ListPaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPaquete setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPaquete setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPaquete set(String parameterName, Object value) {
      return (ListPaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePaquete".
   *
   * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
   * optional parameters, call the {@link RemovePaquete#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePaquete removePaquete(java.lang.String id) throws java.io.IOException {
    RemovePaquete result = new RemovePaquete(id);
    initialize(result);
    return result;
  }

  public class RemovePaquete extends PaqueteendpointRequest<Void> {

    private static final String REST_PATH = "paquete/{id}";

    /**
     * Create a request for the method "removePaquete".
     *
     * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
     * optional parameters, call the {@link RemovePaquete#execute()} method to invoke the remote
     * operation. <p> {@link RemovePaquete#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePaquete(java.lang.String id) {
      super(Paqueteendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePaquete setAlt(java.lang.String alt) {
      return (RemovePaquete) super.setAlt(alt);
    }

    @Override
    public RemovePaquete setFields(java.lang.String fields) {
      return (RemovePaquete) super.setFields(fields);
    }

    @Override
    public RemovePaquete setKey(java.lang.String key) {
      return (RemovePaquete) super.setKey(key);
    }

    @Override
    public RemovePaquete setOauthToken(java.lang.String oauthToken) {
      return (RemovePaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePaquete setQuotaUser(java.lang.String quotaUser) {
      return (RemovePaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePaquete setUserIp(java.lang.String userIp) {
      return (RemovePaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovePaquete setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePaquete set(String parameterName, Object value) {
      return (RemovePaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePaquete".
   *
   * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePaquete#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.fortmin.proshopping.paqueteendpoint.model.Paquete}
   * @return the request
   */
  public UpdatePaquete updatePaquete(com.fortmin.proshopping.paqueteendpoint.model.Paquete content) throws java.io.IOException {
    UpdatePaquete result = new UpdatePaquete(content);
    initialize(result);
    return result;
  }

  public class UpdatePaquete extends PaqueteendpointRequest<com.fortmin.proshopping.paqueteendpoint.model.Paquete> {

    private static final String REST_PATH = "paquete";

    /**
     * Create a request for the method "updatePaquete".
     *
     * This request holds the parameters needed by the the paqueteendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePaquete#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePaquete#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.fortmin.proshopping.paqueteendpoint.model.Paquete}
     * @since 1.13
     */
    protected UpdatePaquete(com.fortmin.proshopping.paqueteendpoint.model.Paquete content) {
      super(Paqueteendpoint.this, "PUT", REST_PATH, content, com.fortmin.proshopping.paqueteendpoint.model.Paquete.class);
    }

    @Override
    public UpdatePaquete setAlt(java.lang.String alt) {
      return (UpdatePaquete) super.setAlt(alt);
    }

    @Override
    public UpdatePaquete setFields(java.lang.String fields) {
      return (UpdatePaquete) super.setFields(fields);
    }

    @Override
    public UpdatePaquete setKey(java.lang.String key) {
      return (UpdatePaquete) super.setKey(key);
    }

    @Override
    public UpdatePaquete setOauthToken(java.lang.String oauthToken) {
      return (UpdatePaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePaquete setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePaquete setUserIp(java.lang.String userIp) {
      return (UpdatePaquete) super.setUserIp(userIp);
    }

    @Override
    public UpdatePaquete set(String parameterName, Object value) {
      return (UpdatePaquete) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Paqueteendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Paqueteendpoint}. */
    @Override
    public Paqueteendpoint build() {
      return new Paqueteendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PaqueteendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPaqueteendpointRequestInitializer(
        PaqueteendpointRequestInitializer paqueteendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(paqueteendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
